language: python

matrix:
  include:
    - name: "Ubuntu"
      os: linux
      dist: bionic
      python:
        - "3.8"

      packages:
        - libxkbcommon-x11-0

      services:
        - xvfb

      install: 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install libx11-dev mesa-common-dev libglu1-mesa-dev

        - python3 -m pip install wheel requests psutil
        - python3 -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python3 -m pip install scikit-image zenframe
        
        - python3 ./setup.py install
        - python3 -m zencad --install-pythonocc-force
        - python3 -m zencad --install-occt-force=utest
        - export LD_LIBRARY_PATH=$PWD/utest:$LD_LIBRARY_PATH

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    - name: "Windows"
      os: "windows"
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8
        - choco install curl        
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - python get-pip.py
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

      services:
        - xvfb

      install: 
        - python -m pip install wheel requests psutil
        - python -m pip install evalcache numpy pillow pyopengl PyQt5 psutil
        - python -m pip install scikit-image zenframe
        
        - python ./setup.py install
        - python -m zencad --install-pythonocc-force
        - python -m zencad --install-occt-to-pythonocc-dir

      script:
        - cd utest
        - python ./api.py
        - python ./examples.py

     # Self Making with Display (Bionic)    PyPi
    - name: "Ubuntu: Loading from pypi"
      if: branch = master
      os: linux
      dist: bionic
      python:
        - "3.8"
            
      services:
        - xvfb

      install: 
        - python3 -m pip install zencad

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py

    - name: "OSX: Loading from pypi"
      if: branch = master
      os: osx
      osx_image: xcode11.2
      language: shell
            
      install: 
        - python3 -m pip install zencad

      script:
        - cd utest
        - python3 ./api.py
        - python3 ./examples.py
